### ISSUE TITLE
Codespaces: Improve researcher documentation

### ISSUE THREAD

**Issue by lucyb** [opensafely-core/research-template-docker#69]
We should make the limitations of Codespaces clearer to researchers, to reduce the risk of them losing work. In particular, we believe the risks are:
1. GitHub automatically deletes inactive Codespaces after 30 days
2. GitHub may remove long running Codespaces (we haven't experienced this, but it's unlikely GitHub would want a Codespace running indefinitely for security and maintenance reasons)
3. Codespaces does experience outages, these are usually short, but it does mean researcher's work may be inaccessible for a period of time.

We have a note at the top of the [How to use Codespaces](https://docs.opensafely.org/getting-started/how-to/use-github-codespaces-in-your-project/) page explaining risk 1. However, it's easy to miss and doesn't cover the other points.

We should ensure our documentation clearly explains the risks, in places where researchers are likely to see it, and points researchers to guidance on pushing their code changes to GitHub.

**Comment by Mary-Anya** [comment]
From the "Codespaces - What to Measure" meeting, we suggested:
- turn some of the text tutorial in to a video tutorial to include lifetimes and definition of the Save button 
- talk about Codespaces lifetimes in the allocated OpenSAFELY conference slot

**Comment by Jongmassey** [comment]
I've been back and forth quite a bit on this ticket and I think what's actually missing from our documentation is a clearly-discoverable introduction to codespaces so that those who use so do so in the knowledge of what they are, what their advantages and limitations are, and what special considerations they should undertake for their use.

We have a [What is a GitHub Codespace](https://docs.opensafely.org/getting-started/explanation/understanding-github-codespaces/) and a page which outlines and compares the [Options for running OpenSAFELY](https://docs.opensafely.org/getting-started/explanation/options-for-running-opensafely/) and the aforementioned [How to use Codespaces](https://docs.opensafely.org/getting-started/how-to/use-github-codespaces-in-your-project/) pages.

I think most, if not all, of the material we want to get across is in these three pages, however it does feel a bit _buried_ in the docs.

I propose we unify the codespaces-related documentation in the docs, make it more concise, and headline the key points about their ephemeral nature, what saving means vs committing and pushing.

An interesting aspect of this is that our proposed _solution_ to the _problem_ of codespaces ephemerality is regular commits and pushing those to GitHub. Most of us would see this as good practice anyway, but I have observed that this is not necessarily shared by many of our research users. I think if we pitch codespaces as "these are a great fit **so long as you undertake good git hygiene**" that is a slightly different proposition that might not appeal to so many.

**Comment by lucyb** [comment]
As a pragmatic solution, to solve the immediate issue of researchers not being aware of the 30 day retention period
