### ISSUE TITLE
Codespaces: Unable to copy-paste into a Codespace

### ISSUE THREAD

**Issue by iaindillingham** [opensafely-core/research-template-docker#75]
@wjchulme was unable to copy-paste into a Codespace and received warnings about extensions not working correctly.

**Comment by Jongmassey** [comment]
I've just started a new codespace from the research-template repo and accessed it via Firefox on Windows 10 and the copy/paste functionality appears to work fine with no warnings or popups

**Comment by Jongmassey** [comment]
I've also started a new codespace from the bennett.ox.ac.uk website and access it via Firefox on Windows 10 and didn't see any of the markdown extension errors also previously experienced by Will

**Comment by iaindillingham** [comment]
Will reports that this issue also occurred when not running in recovery mode.[^1]

[^1]: https://bennettoxford.slack.com/archives/C33TWNQ1J/p1729182626694299?thread_ts=1729177307.365829&cid=C33TWNQ1J

**Comment by lucyb** [comment]
This issue was resolved by creating a new Codespace. I'm not completely sure that Will did experience this issue when not running in recovery mode, unfortunately that thread is very long now. I don't think any further action is required though, given that Will does have copy and paste working now.

Documentation for explaining and resolving this issue added here: https://github.com/opensafely/documentation/pull/1660
